import { useState, useRef, useEffect, useCallback } from "react";

const CW_BLUE = "#003087";
const CW_RED  = "#E4002B";

function CWLogo() {
  return (
    <div style={{ display:"flex", alignItems:"center", gap:0, flexShrink:0 }}>
      <svg width="52" height="46" viewBox="0 0 80 52" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M22 5 C6 5 1 16 3 28 C5 35 9 40 14 43" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M54 5 C70 5 75 16 73 28 C71 35 67 40 62 43" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M22 5 C22 17 30 27 38 34" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M54 5 C54 17 46 27 38 34" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M29 24 L38 38 L47 24" stroke="white" strokeWidth="4.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
      </svg>
      <div style={{ width:1, height:32, background:"rgba(255,255,255,0.3)", margin:"0 12px" }} />
      <span style={{ color:"white", fontFamily:"Arial,sans-serif", fontWeight:"700", fontSize:"17px", letterSpacing:"2px", whiteSpace:"nowrap" }}>
        CONNECTWISE<sup style={{ fontSize:"8px", marginLeft:1 }}>®</sup>
      </span>
    </div>
  );
}

const PRODUCTS = [
  "Cybersecurity / MDR","Cybersecurity / SIEM","Cybersecurity / EDR",
  "Cybersecurity / AI SOC","Cybersecurity / Vulnerability Management",
  "RMM","PSA / ConnectWise Manage","Other",
];

const SECTIONS = [
  "Executive Summary","PRD Summary Table","Objectives & Outcomes","Scope",
  "Partner Segmentation","Feature Comparison","Feature Gaps & Pain Points",
  "Success KPIs","Assumptions & Dependencies","Milestones & Phased Delivery",
  "Personas & Usage Scenarios","Detailed Requirements Table",
  "Non-Functional Requirements","Migration Requirements","Release Readiness",
  "Risks & Mitigation","Quantitative Insights","Out of Scope","Reference Links",
];

const SYSTEM_PROMPT = `You are a senior Product Manager at ConnectWise. ConnectWise serves MSPs, MSSPs, and TSPs (called "partners") who use ConnectWise products for their end clients. Core products: RMM, PSA, MDR, SIEM, EDR, AI SOC, Vulnerability Management.

Generate a complete PRD in Markdown with ALL 19 sections:

# PRD: [Title]
**Version:** 1.0 | **Date:** ${new Date().toLocaleDateString()} | **Status:** Draft

## 1. Executive Summary
## 2. PRD Summary Table
| Field | Details |
|---|---|
| Product Area | |
| Feature Name | |
| Priority | |
| Target Release | |
| PM Owner | |
| Partner Segments | MSP / MSSP / TSP |

## 3. Objectives & Outcomes
### Business Objectives
### Desired Outcomes
### Why Now?

## 4. Scope
### In Scope
### Out of Scope

## 5. Partner Segmentation
| Partner Type | Key Need | Impact |
|---|---|---|
| MSP | | |
| MSSP | | |
| TSP | | |

## 6. Feature Comparison Across Products
| Feature | Current State | Proposed State | Competitor |
|---|---|---|---|

## 7. Feature Gaps and Pain Points
### Feature Gaps
### Migration Challenges
### Display Issues
### Data Integrity Concerns

## 8. Success KPIs
| KPI | Baseline | Target | How Measured |
|---|---|---|---|

## 9. Assumptions & Dependencies
### Assumptions
### Dependencies

## 10. Milestones & Phased Delivery
| Phase | Milestone | Target Date | Owner |
|---|---|---|---|

## 11. Personas and Usage Scenarios
### Primary Persona
### Other Personas
### Key Scenarios
### Step-by-Step Examples

## 12. Detailed Requirements Table
| ID | Requirement | Priority | User Story | Acceptance Criteria |
|---|---|---|---|---|
| REQ-001 | | Must Have | As a partner, I want... | |
(minimum 8 requirements)

## 13. Non-Functional Requirements
| Category | Requirement | Target |
|---|---|---|

## 14. Migration Requirements

## 15. Release Readiness Requirements
| Team | Requirements | Owner |
|---|---|---|

## 16. Risks & Mitigation
| Risk | Likelihood | Impact | Mitigation |
|---|---|---|---|

## 17. Quantitative Insights

## 18. Out of Scope

## 19. Reference Links
| Resource | Link |
|---|---|
| ConnectWise Docs | https://docs.connectwise.com |

---
*Generated by ConnectWise PRD Generator*`;

// ── Markdown Renderer ────────────────────────────────────────────────────────
function MDRenderer({ content }) {
  if (!content) return null;
  const renderInline = (text) =>
    text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((p, i) => {
      if (/^\*\*(.+)\*\*$/.test(p)) return <strong key={i}>{p.replace(/\*\*/g,"")}</strong>;
      if (/^`(.+)`$/.test(p)) return <code key={i} style={{ background:"#f0f4ff", padding:"1px 4px", borderRadius:3, fontSize:12 }}>{p.replace(/`/g,"")}</code>;
      return p;
    });

  const lines = content.split("\n");
  const els = [];
  let i = 0;
  while (i < lines.length) {
    const ln = lines[i];
    if (/^# /.test(ln))   { els.push(<h1 key={i} style={{ fontSize:22, fontWeight:800, color:CW_BLUE, margin:"20px 0 8px", borderBottom:`3px solid ${CW_RED}`, paddingBottom:6 }}>{ln.slice(2)}</h1>); i++; continue; }
    if (/^## /.test(ln))  { els.push(<h2 key={i} style={{ fontSize:16, fontWeight:700, color:CW_BLUE, margin:"18px 0 6px", borderLeft:`4px solid ${CW_RED}`, paddingLeft:10 }}>{ln.slice(3)}</h2>); i++; continue; }
    if (/^### /.test(ln)) { els.push(<h3 key={i} style={{ fontSize:14, fontWeight:700, color:"#222", margin:"12px 0 4px" }}>{ln.slice(4)}</h3>); i++; continue; }
    if (/^---/.test(ln))  { els.push(<hr key={i} style={{ border:"none", borderTop:"1px solid #e0e6f0", margin:"10px 0" }} />); i++; continue; }
    // Table
    if (/^\|/.test(ln) && i+1 < lines.length && /^\|[-| :]+\|/.test(lines[i+1])) {
      const tLines = [];
      while (i < lines.length && /^\|/.test(lines[i])) { tLines.push(lines[i]); i++; }
      const headers = tLines[0].split("|").slice(1,-1).map(c=>c.trim());
      const rows = tLines.slice(2).map(r=>r.split("|").slice(1,-1).map(c=>c.trim())).filter(r=>r.some(c=>c&&!/^[-:]+$/.test(c)));
      els.push(
        <div key={`t${i}`} style={{ overflowX:"auto", margin:"8px 0 14px" }}>
          <table style={{ borderCollapse:"collapse", width:"100%", fontSize:12.5 }}>
            <thead><tr style={{ background:CW_BLUE }}>{headers.map((h,hi)=><th key={hi} style={{ padding:"8px 12px", color:"white", textAlign:"left", whiteSpace:"nowrap" }}>{h}</th>)}</tr></thead>
            <tbody>{rows.map((row,ri)=><tr key={ri} style={{ background:ri%2===0?"#f7f9fd":"white" }}>{row.map((cell,ci)=><td key={ci} style={{ padding:"6px 12px", borderBottom:"1px solid #e8ecf4", verticalAlign:"top" }}>{renderInline(cell)}</td>)}</tr>)}</tbody>
          </table>
        </div>
      );
      continue;
    }
    if (/^[-*] /.test(ln))  { els.push(<li key={i} style={{ marginLeft:20, marginBottom:3, fontSize:13, lineHeight:1.6 }}>{renderInline(ln.replace(/^[-*] /,""))}</li>); i++; continue; }
    if (/^\d+\. /.test(ln)) { els.push(<li key={i} style={{ marginLeft:22, marginBottom:3, fontSize:13, listStyleType:"decimal", lineHeight:1.6 }}>{renderInline(ln.replace(/^\d+\. /,""))}</li>); i++; continue; }
    if (!ln.trim())         { els.push(<div key={i} style={{ height:5 }} />); i++; continue; }
    els.push(<p key={i} style={{ fontSize:13, margin:"2px 0", lineHeight:1.7, color:"#333" }}>{renderInline(ln)}</p>);
    i++;
  }
  return <div style={{ fontFamily:"'Segoe UI',system-ui,sans-serif" }}>{els}</div>;
}

function Chip({ label, color=CW_BLUE }) {
  return <span style={{ background:`${color}18`, color, border:`1px solid ${color}30`, borderRadius:20, padding:"3px 10px", fontSize:11, fontWeight:600 }}>{label}</span>;
}

// ── Main App ─────────────────────────────────────────────────────────────────
export default function App() {
  const [tab,        setTab]        = useState("input");
  const [input,      setInput]      = useState("");
  const [pmName,     setPmName]     = useState("");
  const [product,    setProduct]    = useState(PRODUCTS[0]);
  const [priority,   setPriority]   = useState("High");
  const [prdText,    setPrdText]    = useState("");
  const [loading,    setLoading]    = useState(false);
  const [error,      setError]      = useState("");
  const [progress,   setProgress]   = useState(0);
  const [history,    setHistory]    = useState([]);
  const [viewingHist,setViewingHist]= useState(null);
  const [copied,     setCopied]     = useState(false);
  const outputRef = useRef(null);

  const completedSections = SECTIONS.filter((_,idx) => {
    const n = idx+1;
    return prdText.includes(`## ${n}.`) || prdText.includes(`## ${n} `);
  }).length;

  // ── Generate PRD ────────────────────────────────────────────────────────────
  const generatePRD = async () => {
    if (!input.trim()) { setError("Please describe your requirement."); return; }
    setError(""); setLoading(true); setPrdText(""); setTab("output"); setProgress(10);

    const iv = setInterval(() => setProgress(p => p < 85 ? p + 3 : p), 800);

    try {
      const res = await fetch("/api/generate-prd", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-haiku-4-5",
          max_tokens: 4000,
          system: SYSTEM_PROMPT,
          messages: [{
            role: "user",
            content: `Generate a complete ConnectWise PRD.\n\nProduct: ${product}\nPriority: ${priority}\nPM: ${pmName || "ConnectWise PM"}\n\nRequirement:\n${input}`
          }]
        })
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data?.error || data?.details?.error?.message || `Server error ${res.status}`);
      }

      const text = (data.content || []).map(b => b.text || "").join("");
      if (!text.trim()) throw new Error("Empty response — please try again.");

      clearInterval(iv); setProgress(100);
      setPrdText(text);

      const title = text.match(/^# PRD: (.+)/m)?.[1] || `PRD — ${product}`;
      const entry = {
        id: Date.now(),
        title,
        product,
        priority,
        pmName,
        date: new Date().toLocaleDateString(),
        prd: text,
      };
      setHistory(h => [entry, ...h.slice(0, 19)]);

    } catch (e) {
      clearInterval(iv);
      setError("⚠ " + e.message);
      setTab("input");
    } finally {
      setLoading(false);
      setTimeout(() => setProgress(0), 1000);
    }
  };

  const copyMarkdown = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const printAsPDF = (text) => {
    const win = window.open("", "_blank");
    win.document.write(`
      <html><head><title>ConnectWise PRD</title>
      <style>
        body { font-family: Arial, sans-serif; font-size: 13px; padding: 40px; color: #333; line-height: 1.6; }
        h1 { color: #003087; font-size: 22px; border-bottom: 3px solid #E4002B; padding-bottom: 6px; }
        h2 { color: #003087; font-size: 16px; border-left: 4px solid #E4002B; padding-left: 10px; margin-top: 20px; }
        h3 { font-size: 14px; margin-top: 14px; }
        table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 12px; }
        th { background: #003087; color: white; padding: 8px 10px; text-align: left; }
        td { padding: 6px 10px; border-bottom: 1px solid #e0e6f0; }
        tr:nth-child(even) { background: #f7f9fd; }
        li { margin-bottom: 3px; }
        hr { border: none; border-top: 1px solid #e0e6f0; margin: 10px 0; }
        @media print { body { padding: 20px; } }
      </style></head><body>
      <div id="content"></div>
      <script>
        const md = ${JSON.stringify(text)};
        document.getElementById('content').innerHTML = md
          .replace(/^# (.+)$/gm, '<h1>$1</h1>')
          .replace(/^## (.+)$/gm, '<h2>$1</h2>')
          .replace(/^### (.+)$/gm, '<h3>$1</h3>')
          .replace(/^---$/gm, '<hr/>')
          .replace(/\\*\\*([^*]+)\\*\\*/g, '<strong>$1</strong>')
          .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
          .replace(/^\\d+\\. (.+)$/gm, '<li>$1</li>')
          .replace(/\\n/g, '<br/>');
        setTimeout(() => window.print(), 500);
      </script></body></html>
    `);
    win.document.close();
  };

  const btn = (color, text, onClick, disabled=false) => (
    <button onClick={onClick} disabled={disabled} style={{
      padding:"8px 16px", background:disabled?"#ccc":color, color:"white",
      border:"none", borderRadius:8, fontSize:13, fontWeight:600,
      cursor:disabled?"not-allowed":"pointer", whiteSpace:"nowrap"
    }}>{text}</button>
  );

  const btnOutline = (text, onClick) => (
    <button onClick={onClick} style={{
      padding:"8px 16px", background:"white", color:CW_BLUE,
      border:`1.5px solid ${CW_BLUE}`, borderRadius:8, fontSize:13,
      fontWeight:600, cursor:"pointer", whiteSpace:"nowrap"
    }}>{text}</button>
  );

  return (
    <div style={{ minHeight:"100vh", background:"#f0f4fb", fontFamily:"'Segoe UI',system-ui,sans-serif" }}>

      {/* Header */}
      <header style={{ background:CW_BLUE, height:58, display:"flex", alignItems:"center", padding:"0 28px", boxShadow:"0 2px 12px rgba(0,0,80,.3)", position:"sticky", top:0, zIndex:100 }}>
        <CWLogo />
        <span style={{ marginLeft:16, color:"rgba(255,255,255,.6)", fontSize:13 }}>PRD Generator · Product Management</span>
        {history.length > 0 && (
          <button onClick={()=>setTab("history")} style={{ marginLeft:"auto", background:"rgba(255,255,255,.15)", border:"1px solid rgba(255,255,255,.25)", color:"white", padding:"6px 14px", borderRadius:8, cursor:"pointer", fontSize:12, fontWeight:600 }}>
            📚 History ({history.length})
          </button>
        )}
      </header>

      <div style={{ maxWidth:1100, margin:"0 auto", padding:"24px 20px" }}>

        {/* Tabs */}
        <div style={{ display:"flex", gap:3, marginBottom:22, background:"white", borderRadius:10, padding:4, width:"fit-content", boxShadow:"0 1px 4px rgba(0,0,0,.08)" }}>
          {[
            ["input",   "📝 Input"],
            ["output",  `📄 PRD${prdText ? ` · ${completedSections}/19` : ""}`],
            ["history", `📚 History${history.length ? ` (${history.length})` : ""}`],
          ].map(([id, label]) => (
            <button key={id} onClick={()=>setTab(id)} style={{
              padding:"8px 22px", border:"none", cursor:"pointer", borderRadius:8,
              fontWeight:600, fontSize:13,
              background: tab===id ? CW_BLUE : "transparent",
              color: tab===id ? "white" : "#666",
            }}>{label}</button>
          ))}
        </div>

        {/* ══ INPUT TAB ══ */}
        {tab === "input" && (
          <div style={{ display:"grid", gridTemplateColumns:"1fr 280px", gap:20 }}>
            <div style={{ background:"white", borderRadius:14, padding:28, boxShadow:"0 1px 8px rgba(0,0,0,.08)" }}>
              <h2 style={{ margin:"0 0 20px", color:CW_BLUE, fontSize:19, fontWeight:800 }}>New PRD</h2>

              <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:14, marginBottom:16 }}>
                <div>
                  <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>Product Area *</div>
                  <select value={product} onChange={e=>setProduct(e.target.value)} style={{ width:"100%", padding:"9px 11px", border:"1.5px solid #dde3f0", borderRadius:8, fontSize:13, background:"white", outline:"none" }}>
                    {PRODUCTS.map(p=><option key={p}>{p}</option>)}
                  </select>
                </div>
                <div>
                  <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>Priority</div>
                  <select value={priority} onChange={e=>setPriority(e.target.value)} style={{ width:"100%", padding:"9px 11px", border:"1.5px solid #dde3f0", borderRadius:8, fontSize:13, background:"white", outline:"none" }}>
                    {["High","Medium","Low"].map(p=><option key={p}>{p}</option>)}
                  </select>
                </div>
              </div>

              <div style={{ marginBottom:16 }}>
                <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>PM Name (optional)</div>
                <input value={pmName} onChange={e=>setPmName(e.target.value)} placeholder="e.g. Jane Smith" style={{ width:"100%", padding:"9px 11px", border:"1.5px solid #dde3f0", borderRadius:8, fontSize:13, outline:"none", boxSizing:"border-box" }} />
              </div>

              <div style={{ marginBottom:20 }}>
                <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>Requirement Description *</div>
                <textarea
                  value={input}
                  onChange={e=>{ setInput(e.target.value); setError(""); }}
                  placeholder="Example: We need AI-powered alert triage in our MDR product. Currently SOC analysts manually review every alert causing fatigue and slow response times. We want the system to auto-classify alerts by severity, suggest remediation steps, and suppress false positives. Target: MSP partners managing 50–500 endpoints per client..."
                  rows={9}
                  style={{ width:"100%", padding:"11px 13px", border:`1.5px solid ${error?CW_RED:"#dde3f0"}`, borderRadius:8, fontSize:13, resize:"vertical", lineHeight:1.7, outline:"none", fontFamily:"inherit", boxSizing:"border-box" }}
                />
                {error && <div style={{ color:CW_RED, fontSize:12.5, marginTop:5 }}>{error}</div>}
              </div>

              <button onClick={generatePRD} disabled={loading} style={{
                width:"100%", padding:"13px", fontSize:15, fontWeight:700,
                background: loading ? "#999" : `linear-gradient(135deg,${CW_RED},#c00020)`,
                color:"white", border:"none", borderRadius:9, cursor:loading?"not-allowed":"pointer",
                boxShadow: loading ? "none" : `0 3px 12px ${CW_RED}50`
              }}>
                {loading ? "⚙️ Generating PRD — please wait..." : "🚀 Generate PRD"}
              </button>

              {loading && (
                <div style={{ marginTop:14 }}>
                  <div style={{ display:"flex", justifyContent:"space-between", fontSize:12, color:"#666", marginBottom:5 }}>
                    <span>Building all 19 sections...</span><span>{progress}%</span>
                  </div>
                  <div style={{ height:7, background:"#eee", borderRadius:4, overflow:"hidden" }}>
                    <div style={{ height:"100%", width:`${progress}%`, background:`linear-gradient(90deg,${CW_BLUE},${CW_RED})`, borderRadius:4, transition:"width .5s" }} />
                  </div>
                </div>
              )}
            </div>

            {/* Sidebar */}
            <div style={{ background:"white", borderRadius:12, padding:18, boxShadow:"0 1px 6px rgba(0,0,0,.08)", height:"fit-content" }}>
              <div style={{ fontSize:12, fontWeight:700, color:CW_BLUE, marginBottom:12, textTransform:"uppercase", letterSpacing:.6 }}>19 Sections Generated</div>
              {SECTIONS.map((s,i) => (
                <div key={i} style={{ display:"flex", alignItems:"center", gap:8, padding:"4px 0", borderBottom:i<18?"1px solid #f2f4f9":"none" }}>
                  <div style={{ width:19, height:19, background:`${CW_BLUE}10`, border:`1px solid ${CW_BLUE}25`, borderRadius:4, display:"flex", alignItems:"center", justifyContent:"center", fontSize:9, color:CW_BLUE, fontWeight:800, flexShrink:0 }}>{i+1}</div>
                  <span style={{ fontSize:11.5, color:"#555" }}>{s}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ══ OUTPUT TAB ══ */}
        {tab === "output" && (
          <div>
            {prdText ? (
              <>
                {/* Toolbar */}
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:14, flexWrap:"wrap", gap:10 }}>
                  <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>
                    <Chip label={`✅ ${completedSections}/19 sections`} color="#2e7d32" />
                    <Chip label={product} color={CW_BLUE} />
                    <Chip label={priority} color={priority==="High"?CW_RED:priority==="Medium"?"#e67e00":"#555"} />
                  </div>
                  <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>
                    {btnOutline(copied ? "✅ Copied!" : "📋 Copy Markdown", () => copyMarkdown(prdText))}
                    {btn(CW_BLUE, "🖨 Save as PDF", () => printAsPDF(prdText))}
                    {btn(CW_RED, "+ New PRD", () => { setPrdText(""); setTab("input"); })}
                  </div>
                </div>
                {/* PRD Content */}
                <div ref={outputRef} style={{ background:"white", borderRadius:14, padding:36, boxShadow:"0 1px 8px rgba(0,0,0,.08)", maxHeight:"76vh", overflowY:"auto" }}>
                  <MDRenderer content={prdText} />
                </div>
              </>
            ) : (
              <div style={{ background:"white", borderRadius:14, padding:60, textAlign:"center", boxShadow:"0 1px 8px rgba(0,0,0,.08)" }}>
                <div style={{ fontSize:44, marginBottom:12 }}>📄</div>
                <div style={{ color:"#bbb", fontSize:15, marginBottom:16 }}>No PRD generated yet.</div>
                {btn(CW_BLUE, "← Go to Input", () => setTab("input"))}
              </div>
            )}
          </div>
        )}

        {/* ══ HISTORY TAB ══ */}
        {tab === "history" && (
          <div>
            {viewingHist ? (
              <div>
                {/* History view toolbar */}
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:14, flexWrap:"wrap", gap:10 }}>
                  <button onClick={()=>setViewingHist(null)} style={{ padding:"7px 16px", background:"white", border:"1.5px solid #ccc", color:"#333", borderRadius:8, fontSize:13, cursor:"pointer", fontWeight:600 }}>
                    ← Back to History
                  </button>
                  <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>
                    {btnOutline(copied?"✅ Copied!":"📋 Copy Markdown", ()=>copyMarkdown(viewingHist.prd))}
                    {btn(CW_BLUE, "🖨 Save as PDF", ()=>printAsPDF(viewingHist.prd))}
                    {btn(CW_RED, "Open in PRD View →", ()=>{ setPrdText(viewingHist.prd); setTab("output"); setViewingHist(null); })}
                  </div>
                </div>
                {/* History PRD content */}
                <div style={{ background:"white", borderRadius:14, padding:36, boxShadow:"0 1px 8px rgba(0,0,0,.08)", maxHeight:"76vh", overflowY:"auto" }}>
                  <MDRenderer content={viewingHist.prd} />
                </div>
              </div>
            ) : history.length === 0 ? (
              <div style={{ background:"white", borderRadius:14, padding:60, textAlign:"center", boxShadow:"0 1px 8px rgba(0,0,0,.08)" }}>
                <div style={{ fontSize:44, marginBottom:12 }}>📚</div>
                <div style={{ color:"#bbb", fontSize:15 }}>No PRDs yet. Generate your first one!</div>
              </div>
            ) : (
              <div>
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:16 }}>
                  <span style={{ fontSize:14, fontWeight:600, color:"#555" }}>{history.length} saved PRD{history.length>1?"s":""}</span>
                  <button onClick={()=>{ if(window.confirm("Clear all history?")) setHistory([]); }} style={{ padding:"6px 14px", background:"white", border:"1.5px solid #f44", color:"#f44", borderRadius:8, fontSize:12, cursor:"pointer", fontWeight:600 }}>
                    🗑 Clear All
                  </button>
                </div>
                <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))", gap:14 }}>
                  {history.map(h => (
                    <div key={h.id} onClick={()=>setViewingHist(h)}
                      style={{ background:"white", borderRadius:12, padding:20, boxShadow:"0 1px 6px rgba(0,0,0,.08)", cursor:"pointer", border:"1.5px solid transparent", transition:"all .18s" }}
                      onMouseEnter={e=>{ e.currentTarget.style.borderColor=CW_BLUE; }}
                      onMouseLeave={e=>{ e.currentTarget.style.borderColor="transparent"; }}>
                      <div style={{ fontSize:13.5, fontWeight:700, color:CW_BLUE, marginBottom:8 }}>{h.title}</div>
                      <div style={{ display:"flex", gap:6, flexWrap:"wrap", marginBottom:8 }}>
                        <Chip label={h.product} color={CW_BLUE} />
                        <Chip label={h.priority} color={h.priority==="High"?CW_RED:h.priority==="Medium"?"#e67e00":"#555"} />
                      </div>
                      <div style={{ display:"flex", justifyContent:"space-between" }}>
                        <span style={{ fontSize:11.5, color:"#bbb" }}>{h.date}</span>
                        {h.pmName && <span style={{ fontSize:11.5, color:"#999" }}>by {h.pmName}</span>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

      </div>

      <style>{`
        button:hover { opacity: 0.88; }
        ::-webkit-scrollbar { width:6px; } ::-webkit-scrollbar-thumb { background:#c8d0e0; border-radius:4px; }
        select:focus, input:focus, textarea:focus { border-color: ${CW_BLUE} !important; outline: none; }
      `}</style>
    </div>
  );
}
